on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  # testing:
  #   uses: ./.github/workflows/test.yml
  pre-release:
    runs-on: ubuntu-latest
    # needs: testing
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-pre-release-config.json

  stable:
    runs-on: ubuntu-latest
    # needs: testing
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
