name: Python Tests

on: 
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.4
    
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover -s ./buttercms_python_testing_fork/tests/
